# Use the same base image as your development environment for Node.js
FROM node:16-alpine

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json (or yarn.lock) files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your source code
COPY . .

# Command to run tests, you can customize it according to your test setup
CMD ["npm", "test"]
